const actionTypes = {
  UPDATE_STUDENT_DETAILS: 'UPDATE_STUDENT_DETAILS',
  UPDATE_QUESTIONS_LIST: 'UPDATE_QUESTIONS_LIST',
  UPDATE_SELECTED_QUESTION: 'UPDATE_SELECTED_QUESTION',
};

export { actionTypes };
